HW3
Sindbag/made_hw_algos pull request #2
Opened 2019-11-15 18:07 UTC by Sindbag

6-4: https://contest.yandex.ru/contest/14885/run-report/24102553/
7-4: https://contest.yandex.ru/contest/14885/run-report/25292551/

2019-11-19 22:57 UTC, smatskevich requested changes

2019-11-19 22:57 UTC, smatskevich commented on hw3/task_6_4.cpp
> +    auto* root = new TNode(tmp);
Дерево создается, но не удаляется.

2019-11-19 22:57 UTC, smatskevich commented on hw3/task_6_4.cpp
> +}
Оставляйте перевод строки в конце файла. Потом при добавлении последняя строка не попадет в будущий diff.

2019-11-19 22:57 UTC, smatskevich commented on hw3/task_7_4.cpp
> +    }
Также требуется освобождение памяти.

2019-11-19 22:57 UTC, smatskevich commented on hw3/task_7_4.cpp
> +    class TNode {
Хорошо бы сделать класс для хранения дерева.

2019-11-24 22:34 UTC, smatskevich requested changes
По шестой остался вопрос - нужно избавиться от рекурсии.
Седьмая принята.

2019-11-24 22:34 UTC, smatskevich commented on hw3/task_6_4.cpp
> +    void cutDown(TNode<T>* root) {
Рекурсия запрещена в этой задаче.

2019-11-24 22:34 UTC, smatskevich commented on hw3/task_7_4.cpp
> +    tree.cutDown();
Формально память освободили, но надо было сделать деструктор :)

2019-11-25 21:09 UTC, Sindbag commented on hw3/task_6_4.cpp
> +    template<typename Callback>
не понял, как тут сделать правильно

2019-12-02 21:36 UTC, smatskevich approved these changes
Задача принята, но free на всякий случай поправьте, пожалуйста.

2019-12-02 21:36 UTC, smatskevich commented on hw3/task_6_4.cpp
> +    template<typename Callback>
Именно так правильно

2019-12-02 21:36 UTC, smatskevich commented on hw3/task_6_4.cpp
> +        traversalCb(free);
free нельзя использовать, если память выделялась с помощью new. Нужен delete. Не заметил, но в седьмой та же проблема.

2019-12-02 21:51 UTC, merged