HW5
Sindbag/made_hw_algos pull request #4
Opened 2019-12-01 00:08 UTC by Sindbag

https://contest.yandex.ru/contest/15964/run-report/27497493/

2019-12-08 20:42 UTC, Sindbag commented on hw5/task_9_1.cpp
> +                    if (left != nullptr) left->buildMapping(mapper, prefix + 'l');
можно вынести константы

2019-12-08 20:42 UTC, Sindbag commented on hw5/task_9_1.cpp
> +            void buildReverseMapping(map<std::string, byte>& mapper, const std::string& prefix) const {
можно завести лямбду на первую ветку ифа и объединить с предыдущим методом

2019-12-09 22:52 UTC, smatskevich requested changes
Поправьте, пожалуйста.

2019-12-09 22:52 UTC, smatskevich commented on hw5/task_9_1.cpp
> +            void buildMapping(map<byte, std::string>& mapper, const std::string& prefix) const {
Реализовывайте методы вне класса.

2019-12-09 22:52 UTC, smatskevich commented on hw5/task_9_1.cpp
> +            tree = new THuffmanTree(data);
Дерево создано, но не разрушено.

2019-12-09 22:52 UTC, smatskevich commented on hw5/task_9_1.cpp
> +            tree = new THuffmanTree(input);
Снова дерево не разрушено.

2019-12-15 00:23 UTC, smatskevich approved these changes
Принято

2019-12-15 00:23 UTC, smatskevich commented on hw5/task_9_1.cpp
> +int main() {
Вместе с main не компилировалось. :)

2019-12-16 08:34 UTC, merged